[build]
  command = "cd /opt/build/repo && pnpm i && pnpm run build"
  publish = "dist"

[dev]
  command = "pnpm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"